"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krS8g1waGFsuH-mrTKjqayGoU8goxghg

Archit Agrawal
202051213
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install joypy
!pip install squarify
!pip install plotly

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import transforms
from statsmodels.graphics.mosaicplot import mosaic
from joypy import joyplot #!pip install joypy
import squarify # pip install squarify
import plotly.express as px # pip install plotly

filename = '/content/drive/MyDrive/data/Lab5/heart.csv'
data=pd.read_csv(filename)
data

"""# Task 1: Plot correlogram to check relationship amongst various measures."""

g = sns.PairGrid(data[['age','trestbps','chol','thalach', 'oldpeak']])
g.map(sns.scatterplot)

"""# Task 2: Draw Heat map to check relationships amongst various measures."""

ax = sns.heatmap(data.corr())